# Generated by Django 5.0.6 on 2024-06-07 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bicycle',
            name='en_el_carrito',
            field=models.BooleanField(default=False),
        ),
    ]
